### ISSUE TITLE
Websocket keeps forcing close connection

### ISSUE THREAD

**Issue by hjeanty** [mgcrea/cake_websocket#2]
Hi, I think there is an error in your code where if the connection type is not set it send a request header where the connection type is forced close. I had to fix it my manually changing the connection type to keep alive, and control the close connection from the server end.

**Comment by fr0z3nfyr** [comment]
What is the solution to this? I face the same issue. The fix suggested by @hjeanty stops from disconnection but then I cake complains about `Sec-WebSocket-Accept` pretty much similar to @hjeanty last comment but not the same.
